import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import '@/app/globals.css';
import Navbar from '@/components/Navbar';
import { ThemeProvider } from '@/components/theme/theme-provider';
import { connectDB } from '@/db/models';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   connectDB();
   return (
      <html lang="en" suppressHydrationWarning={true}>
         <body className={`${inter.className} antialiased`}>
            <ThemeProvider
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
            >
               <Navbar sideMenu={false} />
               <main>{children}</main>
            </ThemeProvider>
         </body>
      </html>
   );
}
